In [28]:
#filter
import numpy as np
arr=np.array([10,20,30,6,2,3])
arr_f=arr[arr!=6]
print(arr_f)

#example  and opr 10 se 20 ke range me
arr1=np.array([10,11,14,1,24,10,17,20])
print(arr1[(arr1<20)&(arr1>10)])

[10 20 30  2  3]
[11 14 17]


In [29]:
#fancy indexing 
import numpy as np
arr=np.array([10,20,3,4,90,100])
print(arr)
arr_f=arr[[0,2]] #0 index value , 2 index value
print(arr_f)

[ 10  20   3   4  90 100]
[10  3]


In [30]:
#question 10 - 20 , *2 -> +2
arr = np.array([10,20,3,4,14,15,16,90,100])
print(arr)
arr_w = np.where((arr>10) & (arr<20),arr*2,arr+2)
print(arr_w)


[ 10  20   3   4  14  15  16  90 100]
[ 12  22   5   6  28  30  32  92 102]


In [31]:
#concatenate using 1D
import numpy as np
arr1=np.array([10,20,30])
arr2=np.array([1,2,3])

#concatenate
arr_arr2=np.concatenate((arr1,arr2))
print(arr_arr2)

#concatenate using 2D
import numpy as np
arr1=np.array([[10,20,30],[40,50,60]])
arr2=np.array([[1,2,3],[4,5,6]])
#by default row wise
print(np.concatenate((arr1,arr2),axis=0))  #row wise
print(np.concatenate((arr1,arr2),axis=1))  #column wise


[10 20 30  1  2  3]
[[10 20 30]
 [40 50 60]
 [ 1  2  3]
 [ 4  5  6]]
[[10 20 30  1  2  3]
 [40 50 60  4  5  6]]


In [32]:
#vstack --> vertically join or row wise 

import numpy as np 
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
result=np.vstack((arr1,arr2))
print(result)


[[1 2 3]
 [4 5 6]]


In [33]:
#hstack --> horizontally or column wise

import numpy as np 
arr1=np.array([10,20,30])
arr2=np.array([40,50,60])
print(np.hstack((arr1,arr2)))

#2d

import numpy as np
arr1=np.array([[10,20,30],[40,50,60]])
arr2=np.array([[1,2,3],[4,5,6]])
print(np.hstack((arr1,arr2)))

[10 20 30 40 50 60]
[[10 20 30  1  2  3]
 [40 50 60  4  5  6]]


#Statistical function



np.sum(a) -> Sum of all elements

np.mean(a) -> Average = Sum of elements / Number of elements

np.median(a) -> Middle value after sorting

np.min(a) -> Smallest value in array

np.max(a) -> Largest value in array

np.var(a) mean,difference,square,average | (sum = ddof) -> divide by array length

np.std(a) -> Standard Deviation = √Variance -> Measures spread of data

np.prod(a) -> Multiplication of all elements

np.cumsum(a) -> Cumulative (running) sum

np.cumprod(a) -> Cumulative (running) product

np.argmin(a) -> Index position of minimum value

np.argmax(a) -> Index position of maximum value

np.abs(a) -> Converts negative values to positive -> Absolute value (distance from zero)

np.unique(a) -> Returns unique values only -> Removes duplicates

np.percentile(a, 50) -> Finds percentage-based value -> 50th percentile = Median

np.quantile(a, 0.5) -> Similar to percentile -> 0.5 = 50%

np.ptp(a) -> Range = Max - Min

np.any(a) -> True if at least one value is True

In [34]:
import numpy as np
arr=np.array([10,20,3,4,90,100])

#sum
print(np.sum(arr))
#mean
print(np.mean(arr))
#median
print(np.median(arr))
#max
print(np.max(arr))
#min
print(np.min(arr))

227
37.833333333333336
15.0
100
3


In [35]:
import numpy as np

arr = np.array([10,20,3,4,90,100])

print("Sum =", np.sum(arr))
print("Mean =", np.mean(arr))
print("Median =", np.median(arr))
print("Max =", np.max(arr))
print("Min =", np.min(arr))

print("Variance =", np.var(arr))
print("Standard Deviation =", np.std(arr))

print("Product =", np.prod(arr))

print("Cumulative Sum =", np.cumsum(arr))
print("Cumulative Product =", np.cumprod(arr))

print("Index of Min =", np.argmin(arr))
print("Index of Max =", np.argmax(arr))

print("Absolute Value =", np.abs(arr))

print("Unique Values =", np.unique(arr))

print("50th Percentile =", np.percentile(arr, 50))

print("Quantile (0.5) =", np.quantile(arr, 0.5))

print("Range =", np.ptp(arr))

print("Any =", np.any(arr))

Sum = 227
Mean = 37.833333333333336
Median = 15.0
Max = 100
Min = 3
Variance = 1672.8055555555554
Standard Deviation = 40.89994566690224
Product = 21600000
Cumulative Sum = [ 10  30  33  37 127 227]
Cumulative Product = [      10      200      600     2400   216000 21600000]
Index of Min = 2
Index of Max = 5
Absolute Value = [ 10  20   3   4  90 100]
Unique Values = [  3   4  10  20  90 100]
50th Percentile = 15.0
Quantile (0.5) = 15.0
Range = 97
Any = True


Handling Missing Value

In [36]:
import numpy as np
arr=np.array([10,20,np.nan,40])
print(arr)

#isnan
print(np.isnan(arr))

#update nan to number 
new_arr=np.nan_to_num(arr,nan=100)
print(new_arr)

#remove 

[10. 20. nan 40.]
[False False  True False]
[ 10.  20. 100.  40.]


ASSIGNMENT

In [ ]:
#Data Structure : [restaurant_id,2021,2022,2023,2024]
import numpy as np
sales_data = np.array([
    [1, 150000, 180000, 220000, 250000],  #Paradise Biryani
    [2, 120000, 140000, 160000, 190000],  #Beijing Bites
    [3, 200000, 230000, 260000, 300000],  #Pizza Hub
    [4, 180000, 210000, 240000, 270000],  #Burger Point
    [5, 160000, 185000, 205000, 230000]   #Chai Point
])
print(" 1 --> Complete dataset  :\n" ,sales_data)
print("2 -> Shape of Array : ",sales_data.shape)
print("3 -> Nummber of Dimensions :",sales_data.ndim)
print("4 -> Total number of Elements :",sales_data.size)
print("5 -> Restaurant IDs :\n",sales_data[:,0])
print("6 -> 2021 sales data :\n",sales_data[:,1])
print("7 -> 2024 sales data :\n",sales_data[:,-1])
print("8 -> Max sales Value :",np.max(sales_data[:,1:]))
print("9 -> Min sales Value :",np.min(sales_data[:,1:]))
print("10 -> Total sales in 2021 :",np.sum(sales_data[:,1]))
print("11 -> Avg sales in 2024 :",np.average(sales_data[:,-1]))
print("12 -> Total sales of each restaurant :\n",np.sum(sales_data[:,1:],axis=1))
print("13 -> Avg sales of each restaurant :\n",np.average(sales_data[:,1:],axis=1))

 1 --> Complete dataset  :
 [[     1 150000 180000 220000 250000]
 [     2 120000 140000 160000 190000]
 [     3 200000 230000 260000 300000]
 [     4 180000 210000 240000 270000]
 [     5 160000 185000 205000 230000]]
2 -> Shape of Array :  (5, 5)
3 -> Nummber of Dimensions : 2
4 -> Total number of Elements : 25
5 -> Restaurant IDs :
 [1 2 3 4 5]
6 -> 2021 sales data :
 [150000 120000 200000 180000 160000]
7 -> 2024 sales data :
 [250000 190000 300000 270000 230000]
8 -> Max sales Value : 300000
9 -> Min sales Value : 120000
10 -> Total sales in 2021 : 810000
11 -> Avg sales in 2024 : 248000.0
12 -> Total sales of each restaurant :
 [800000 610000 990000 900000 780000]
13 -> Avg sales of each restaurant :
 [200000. 152500. 247500. 225000. 195000.]
