In [2]:
# File handling basics

# Writing to a file
with open('example.txt', 'w') as file:
    file.write('Hello, World!\n')
    file.write('This is a test file.')

# Reading from a file
with open('example.txt', 'r') as file:
    content = file.read()
    print(content)

# Reading line by line
with open('example.txt', 'r') as file:
    for line in file:
        print(line.strip())

# Appending to a file
with open('example.txt', 'a') as file:
    file.write('\nAppended text.')

Hello, World!
This is a test file.
Hello, World!
This is a test file.


In [ ]:
#read a file

with open('hello.txt', 'r') as file:
    content=file.read()
    print(content)

Hello File Handling



In [ ]:
#read a file 

data = open('hello.txt','r')
data.read()

'Hello File Handling\n'

In [8]:
#update content in a file 

data = open('hello.txt','w')
data.write('My name is Aditya rao\n')
data = open('hello.txt','r')
data.read()

'My name is Aditya rao\n'

In [16]:
#append
with open('hello.txt','a') as f:
    print(f.write("Btech 3rd yr student"))


20


In [17]:
with open('hello.txt', 'r') as file:
    content=file.read()
    print(content)

My name is Aditya rao
Btech 3rd yr student


In [18]:
#direct access csv file 
data1=open('file1.csv','r')
print(data1.read())

name,roll no
dheeraj,123
kunal,1234
abhishek,12345
praveen,12356
anjali,1234567


Numpy

In [19]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.


In [1]:
import numpy as np
# 1d
l = [10,20,30,40]
l*2

[10, 20, 30, 40, 10, 20, 30, 40]

In [2]:
# power of numpy
arr = np.array(l)
arr*2

array([20, 40, 60, 80])

In [3]:

import numpy as np
arr = np.array([1,2,3,4])
print(arr)
print(arr[0])
print(arr[-1])

[1 2 3 4]
1
4


In [4]:
import numpy as np
# check type
l = [10,20,30,40]
print(l)
print(type(l))

arr = np.array(l)
print(arr)
print(type(arr))

[10, 20, 30, 40]
<class 'list'>
[10 20 30 40]
<class 'numpy.ndarray'>


In [5]:
# change value
import numpy as np
l = [10,20,30,40]
l[0] = 100
l[-1] = 150
print(l)
# numpy
arr = np.array(l)
arr[0] = 200
arr[-1] = 250
print(arr)

[100, 20, 30, 150]
[200  20  30 250]


In [6]:
# value add = 2
import numpy as np
l = [10,20,30,40]
# print(l+2) # add not acceptable with list

arr = np.array(l)
print(arr+2)

[12 22 32 42]


In [7]:
# arange in numpy
import numpy as np
arr = np.arange(5) # start,stop,jump
print(arr)

arr = np.arange(1,7,2)
print(arr)

[0 1 2 3 4]
[1 3 5]


In [8]:
for i in range(1,5):
  print(i)

1
2
3
4


In [9]:
# simple 2d example
import numpy as np
print("list start")
l = [[1,2,3],[4,5,6]]
print(l)
print(l[0][1]) # -> 2
print("numpy start")
# numpy 2d
arr = np.array(l)
print(arr)
print(arr[0][0])

list start
[[1, 2, 3], [4, 5, 6]]
2
numpy start
[[1 2 3]
 [4 5 6]]
1
